# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    
    - uses: browser-actions/setup-firefox@latest
    - run: firefox --version
    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Running Automated Tests
      run: mvn -B clean test verify -Dheadless=true --file pom.xml

    - uses: actions/upload-artifact@v2
      with:
        name: Tests Automated Report
        path: report/cucumber-html-reports/
        if-no-files-found: error
      

